---
services:
  besu:
    image: hyperledger/besu:latest
    container_name: besu-node
    ports:
      - "8545:8545"   # HTTP JSON-RPC
      - "8546:8546"   # WebSocket
      - "30303:30303" # P2P
    volumes:
      - ./data/besu:/var/lib/besu
    command: >
      --network=dev
      --data-path=/var/lib/besu
      --rpc-http-enabled
      --rpc-http-host=0.0.0.0
      --rpc-http-port=8545
      --rpc-ws-enabled
      --rpc-ws-port=8546
      --host-allowlist=*

  ipfs:
    image: ipfs/kubo:latest
    container_name: ipfs-node
    ports:
      - "4001:4001"
      - "4001:4001/udp"
      - "5001:5001"
      - "8080:8080"
    volumes:
      - ./data/ipfs:/data/ipfs
      - ./swarm.key:/data/ipfs/swarm.key:ro
    command: daemon --migrate=true